# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_pipeline_trigger.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafettePipelineTrigger" do
    optional :event, :string, 1
    optional :status, :string, 2
    optional :name, :string, 3
    optional :branch, :string, 4
  end
end

module Manifest
  module V1
    EstafettePipelineTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafettePipelineTrigger").msgclass
  end
end
