# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_trigger_build_action.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteTriggerBuildAction" do
    optional :branch, :string, 1
  end
end

module Manifest
  module V1
    EstafetteTriggerBuildAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteTriggerBuildAction").msgclass
  end
end
