# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_pub_sub_trigger.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafettePubSubTrigger" do
    optional :project, :string, 1
    optional :topic, :string, 2
  end
end

module Manifest
  module V1
    EstafettePubSubTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafettePubSubTrigger").msgclass
  end
end
