# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_manifest.proto

require 'google/protobuf'

require 'protos/manifest.v1/estafette_builder_pb'
require 'protos/manifest.v1/estafette_release_pb'
require 'protos/manifest.v1/estafette_stage_pb'
require 'protos/manifest.v1/estafette_trigger_pb'
require 'protos/manifest.v1/estafette_version_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteManifest" do
    optional :builder, :message, 1, "manifest.v1.EstafetteBuilder"
    map :labels, :string, :string, 2
    optional :version, :message, 3, "manifest.v1.EstafetteVersion"
    map :global_env_vars, :string, :string, 4
    repeated :triggers, :message, 5, "manifest.v1.EstafetteTrigger"
    repeated :stages, :message, 6, "manifest.v1.EstafetteStage"
    repeated :releases, :message, 7, "manifest.v1.EstafetteRelease"
  end
end

module Manifest
  module V1
    EstafetteManifest = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteManifest").msgclass
  end
end
