# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_manual_event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteManualEvent" do
    optional :user_id, :string, 1
  end
end

module Manifest
  module V1
    EstafetteManualEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteManualEvent").msgclass
  end
end
