# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_event.proto

require 'google/protobuf'

require 'protos/manifest.v1/estafette_cron_event_pb'
require 'protos/manifest.v1/estafette_docker_event_pb'
require 'protos/manifest.v1/estafette_git_event_pb'
require 'protos/manifest.v1/estafette_manual_event_pb'
require 'protos/manifest.v1/estafette_pipeline_event_pb'
require 'protos/manifest.v1/estafette_pub_sub_event_pb'
require 'protos/manifest.v1/estafette_release_event_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteEvent" do
    optional :pipeline, :message, 1, "manifest.v1.EstafettePipelineEvent"
    optional :release, :message, 2, "manifest.v1.EstafetteReleaseEvent"
    optional :git, :message, 3, "manifest.v1.EstafetteGitEvent"
    optional :docker, :message, 4, "manifest.v1.EstafetteDockerEvent"
    optional :cron, :message, 5, "manifest.v1.EstafetteCronEvent"
    optional :pub_sub, :message, 6, "manifest.v1.EstafettePubSubEvent"
    optional :manual, :message, 7, "manifest.v1.EstafetteManualEvent"
  end
end

module Manifest
  module V1
    EstafetteEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteEvent").msgclass
  end
end
