# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_pub_sub_event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafettePubSubEvent" do
    optional :project, :string, 1
    optional :topic, :string, 2
  end
end

module Manifest
  module V1
    EstafettePubSubEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafettePubSubEvent").msgclass
  end
end
