# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_cron_trigger.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteCronTrigger" do
    optional :schedule, :string, 1
  end
end

module Manifest
  module V1
    EstafetteCronTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteCronTrigger").msgclass
  end
end
