# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_release.proto

require 'google/protobuf'

require 'protos/manifest.v1/estafette_release_action_pb'
require 'protos/manifest.v1/estafette_stage_pb'
require 'protos/manifest.v1/estafette_trigger_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteRelease" do
    optional :name, :string, 1
    optional :clone_repository, :bool, 2
    repeated :actions, :message, 3, "manifest.v1.EstafetteReleaseAction"
    repeated :triggers, :message, 4, "manifest.v1.EstafetteTrigger"
    repeated :stages, :message, 5, "manifest.v1.EstafetteStage"
  end
end

module Manifest
  module V1
    EstafetteRelease = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteRelease").msgclass
  end
end
