# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/manifest.v1/estafette_release_action.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteReleaseAction" do
    optional :name, :string, 1
  end
end

module Manifest
  module V1
    EstafetteReleaseAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteReleaseAction").msgclass
  end
end
