# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_git_event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("estafette/ci/manifest/v1/estafette_git_event.proto", :syntax => :proto3) do
    add_message "estafette.ci.manifest.v1.EstafetteGitEvent" do
      optional :event, :string, 1
      optional :repository, :string, 2
      optional :branch, :string, 3
    end
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteGitEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteGitEvent").msgclass
      end
    end
  end
end
