# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_pub_sub_trigger.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.manifest.v1.EstafettePubSubTrigger" do
    optional :project, :string, 1
    optional :topic, :string, 2
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafettePubSubTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafettePubSubTrigger").msgclass
      end
    end
  end
end
