# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_release_action.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.manifest.v1.EstafetteReleaseAction" do
    optional :name, :string, 1
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteReleaseAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteReleaseAction").msgclass
      end
    end
  end
end
