# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_cron_event.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("estafette/ci/manifest/v1/estafette_cron_event.proto", :syntax => :proto3) do
    add_message "estafette.ci.manifest.v1.EstafetteCronEvent" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
    end
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteCronEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteCronEvent").msgclass
      end
    end
  end
end
