# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_manual_event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.manifest.v1.EstafetteManualEvent" do
    optional :user_id, :string, 1
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteManualEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteManualEvent").msgclass
      end
    end
  end
end
