# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_builder.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.manifest.v1.EstafetteBuilder" do
    optional :track, :string, 1
    optional :operating_system, :string, 2
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteBuilder = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteBuilder").msgclass
      end
    end
  end
end
