# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_trigger_release_action.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("estafette/ci/manifest/v1/estafette_trigger_release_action.proto", :syntax => :proto3) do
    add_message "estafette.ci.manifest.v1.EstafetteTriggerReleaseAction" do
      optional :target, :string, 1
      optional :action, :string, 2
      optional :version, :string, 3
    end
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteTriggerReleaseAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteTriggerReleaseAction").msgclass
      end
    end
  end
end
