# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_custom_version.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("estafette/ci/manifest/v1/estafette_custom_version.proto", :syntax => :proto3) do
    add_message "estafette.ci.manifest.v1.EstafetteCustomVersion" do
      optional :label_template, :string, 1
    end
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteCustomVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteCustomVersion").msgclass
      end
    end
  end
end
