# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_manifest.proto

require 'google/protobuf'

require 'estafette/ci/manifest/v1/estafette_builder_pb'
require 'estafette/ci/manifest/v1/estafette_release_pb'
require 'estafette/ci/manifest/v1/estafette_stage_pb'
require 'estafette/ci/manifest/v1/estafette_trigger_pb'
require 'estafette/ci/manifest/v1/estafette_version_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.manifest.v1.EstafetteManifest" do
    optional :builder, :message, 1, "estafette.ci.manifest.v1.EstafetteBuilder"
    map :labels, :string, :string, 2
    optional :version, :message, 3, "estafette.ci.manifest.v1.EstafetteVersion"
    map :global_env_vars, :string, :string, 4
    repeated :triggers, :message, 5, "estafette.ci.manifest.v1.EstafetteTrigger"
    repeated :stages, :message, 6, "estafette.ci.manifest.v1.EstafetteStage"
    repeated :releases, :message, 7, "estafette.ci.manifest.v1.EstafetteRelease"
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteManifest = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteManifest").msgclass
      end
    end
  end
end
