# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/manifest/v1/estafette_semver_version.proto

require 'google/protobuf'

require 'estafette/ci/manifest/v1/string_or_string_array_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.manifest.v1.EstafetteSemverVersion" do
    optional :major, :int64, 1
    optional :minor, :int64, 2
    optional :patch, :string, 3
    optional :label_template, :string, 4
    optional :release_branch, :message, 5, "estafette.ci.manifest.v1.StringOrStringArray"
  end
end

module Estafette
  module Ci
    module Manifest
      module V1
        EstafetteSemverVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.manifest.v1.EstafetteSemverVersion").msgclass
      end
    end
  end
end
