# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/build_params_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.BuildParamsConfig" do
    optional :build_id, :int64, 1
  end
end

module Contracts
  module V1
    BuildParamsConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.BuildParamsConfig").msgclass
  end
end
