# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/container_repository_credential_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.ContainerRepositoryCredentialConfig" do
    optional :repository, :string, 1
    optional :username, :string, 2
    optional :password, :string, 3
  end
end

module Contracts
  module V1
    ContainerRepositoryCredentialConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.ContainerRepositoryCredentialConfig").msgclass
  end
end
