# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/git_commit.proto

require 'google/protobuf'

require 'contracts.v1/git_author_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.GitCommit" do
    optional :message, :string, 1
    optional :author, :message, 2, "contracts.v1.GitAuthor"
  end
end

module Contracts
  module V1
    GitCommit = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.GitCommit").msgclass
  end
end
