# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/pagination.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.Pagination" do
    optional :page, :int64, 1
    optional :size, :int64, 2
    optional :total_pages, :int64, 3
    optional :total_items, :int64, 4
  end
end

module Contracts
  module V1
    Pagination = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.Pagination").msgclass
  end
end
