# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/release_log.proto

require 'google/protobuf'

require 'contracts.v1/build_log_step_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.ReleaseLog" do
    optional :id, :string, 1
    optional :repo_source, :string, 2
    optional :repo_owner, :string, 3
    optional :repo_name, :string, 4
    optional :release_id, :string, 5
    repeated :steps, :message, 6, "contracts.v1.BuildLogStep"
    optional :inserted_at, :message, 7, "google.protobuf.Timestamp"
  end
end

module Contracts
  module V1
    ReleaseLog = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.ReleaseLog").msgclass
  end
end
