# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.v1/trusted_image_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.TrustedImageConfig" do
    optional :image_path, :string, 1
    optional :run_privileged, :bool, 2
    optional :run_docker, :bool, 3
    optional :allow_commands, :bool, 4
    repeated :injected_credential_types, :string, 5
  end
end

module Contracts
  module V1
    TrustedImageConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.TrustedImageConfig").msgclass
  end
end
