# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/build_params_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.contracts.v1.BuildParamsConfig" do
    optional :build_id, :int64, 1
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        BuildParamsConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.BuildParamsConfig").msgclass
      end
    end
  end
end
