# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/build_version_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.contracts.v1.BuildVersionConfig" do
    optional :version, :string, 1
    optional :major, :int64, 2
    optional :minor, :int64, 3
    optional :patch, :string, 4
    optional :label, :string, 5
    optional :auto_increment, :int64, 6
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        BuildVersionConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.BuildVersionConfig").msgclass
      end
    end
  end
end
