# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/ci_server_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.contracts.v1.CiServerConfig" do
    optional :base_url, :string, 1
    optional :builder_events_url, :string, 2
    optional :post_logs_url, :string, 3
    optional :api_key, :string, 4
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        CiServerConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.CiServerConfig").msgclass
      end
    end
  end
end
