# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/container_repository_credential_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.contracts.v1.ContainerRepositoryCredentialConfig" do
    optional :repository, :string, 1
    optional :username, :string, 2
    optional :password, :string, 3
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        ContainerRepositoryCredentialConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.ContainerRepositoryCredentialConfig").msgclass
      end
    end
  end
end
