# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/git_author.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("estafette/ci/contracts/v1/git_author.proto", :syntax => :proto3) do
    add_message "estafette.ci.contracts.v1.GitAuthor" do
      optional :email, :string, 1
      optional :name, :string, 2
      optional :username, :string, 3
    end
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        GitAuthor = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.GitAuthor").msgclass
      end
    end
  end
end
