# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/git_commit.proto

require 'google/protobuf'

require 'estafette/ci/contracts/v1/git_author_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("estafette/ci/contracts/v1/git_commit.proto", :syntax => :proto3) do
    add_message "estafette.ci.contracts.v1.GitCommit" do
      optional :message, :string, 1
      optional :author, :message, 2, "estafette.ci.contracts.v1.GitAuthor"
    end
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        GitCommit = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.GitCommit").msgclass
      end
    end
  end
end
