# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/release_log.proto

require 'google/protobuf'

require 'estafette/ci/contracts/v1/build_log_step_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.contracts.v1.ReleaseLog" do
    optional :id, :string, 1
    optional :repo_source, :string, 2
    optional :repo_owner, :string, 3
    optional :repo_name, :string, 4
    optional :release_id, :string, 5
    repeated :steps, :message, 6, "estafette.ci.contracts.v1.BuildLogStep"
    optional :inserted_at_time, :message, 7, "google.protobuf.Timestamp"
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        ReleaseLog = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.ReleaseLog").msgclass
      end
    end
  end
end
