# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/trusted_image_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("estafette/ci/contracts/v1/trusted_image_config.proto", :syntax => :proto3) do
    add_message "estafette.ci.contracts.v1.TrustedImageConfig" do
      optional :image_path, :string, 1
      optional :run_privileged, :bool, 2
      optional :run_docker, :bool, 3
      optional :allow_commands, :bool, 4
      repeated :injected_credential_types, :string, 5
    end
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        TrustedImageConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.TrustedImageConfig").msgclass
      end
    end
  end
end
