# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estafette/ci/contracts/v1/warning.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "estafette.ci.contracts.v1.Warning" do
    optional :status, :string, 1
    optional :message, :string, 2
  end
end

module Estafette
  module Ci
    module Contracts
      module V1
        Warning = Google::Protobuf::DescriptorPool.generated_pool.lookup("estafette.ci.contracts.v1.Warning").msgclass
      end
    end
  end
end
