# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/build_log.proto

require 'google/protobuf'

require 'protos/contracts.v1/build_log_step_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.BuildLog" do
    optional :id, :string, 1
    optional :repo_source, :string, 2
    optional :repo_owner, :string, 3
    optional :repo_name, :string, 4
    optional :repo_branch, :string, 5
    optional :repo_revision, :string, 6
    optional :build_id, :string, 7
    repeated :steps, :message, 8, "contracts.v1.BuildLogStep"
    optional :inserted_at, :message, 9, "google.protobuf.Timestamp"
  end
end

module Contracts
  module V1
    BuildLog = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.BuildLog").msgclass
  end
end
