# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/ci_server_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.CIServerConfig" do
    optional :base_url, :string, 1
    optional :builder_events_url, :string, 2
    optional :post_logs_url, :string, 3
    optional :api_key, :string, 4
  end
end

module Contracts
  module V1
    CIServerConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.CIServerConfig").msgclass
  end
end
