# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/git_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.GitConfig" do
    optional :repo_source, :string, 1
    optional :repo_owner, :string, 2
    optional :repo_name, :string, 3
    optional :repo_branch, :string, 4
    optional :repo_revision, :string, 5
  end
end

module Contracts
  module V1
    GitConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.GitConfig").msgclass
  end
end
