# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/git_author.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.GitAuthor" do
    optional :email, :string, 1
    optional :name, :string, 2
    optional :username, :string, 3
  end
end

module Contracts
  module V1
    GitAuthor = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.GitAuthor").msgclass
  end
end
