# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/label.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.Label" do
    optional :key, :string, 1
    optional :value, :string, 2
  end
end

module Contracts
  module V1
    Label = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.Label").msgclass
  end
end
