# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/list_response.proto

require 'google/protobuf'

require 'protos/contracts.v1/pagination_pb'
require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.ListResponse" do
    repeated :items, :message, 1, "google.protobuf.Any"
    optional :pagination, :message, 2, "contracts.v1.Pagination"
  end
end

module Contracts
  module V1
    ListResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.ListResponse").msgclass
  end
end
