# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/release_params_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.ReleaseParamsConfig" do
    optional :release_name, :string, 1
    optional :release_id, :int64, 2
    optional :release_action, :string, 3
    optional :triggered_by, :string, 4
  end
end

module Contracts
  module V1
    ReleaseParamsConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.ReleaseParamsConfig").msgclass
  end
end
