# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contracts.v1/warning.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "contracts.v1.Warning" do
    optional :status, :string, 1
    optional :message, :string, 2
  end
end

module Contracts
  module V1
    Warning = Google::Protobuf::DescriptorPool.generated_pool.lookup("contracts.v1.Warning").msgclass
  end
end
