# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.v1/estafette_cron_event.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteCronEvent" do
    optional :time, :message, 1, "google.protobuf.Timestamp"
  end
end

module Manifest
  module V1
    EstafetteCronEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteCronEvent").msgclass
  end
end
