# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.v1/estafette_trigger_release_action.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteTriggerReleaseAction" do
    optional :target, :string, 1
    optional :action, :string, 2
    optional :version, :string, 3
  end
end

module Manifest
  module V1
    EstafetteTriggerReleaseAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteTriggerReleaseAction").msgclass
  end
end
