# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.v1/estafette_git_event.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.EstafetteGitEvent" do
    optional :event, :string, 1
    optional :repository, :string, 2
    optional :branch, :string, 3
  end
end

module Manifest
  module V1
    EstafetteGitEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.EstafetteGitEvent").msgclass
  end
end
