# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.v1/string_or_string_array.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "manifest.v1.StringOrStringArray" do
    repeated :values, :string, 1
  end
end

module Manifest
  module V1
    StringOrStringArray = Google::Protobuf::DescriptorPool.generated_pool.lookup("manifest.v1.StringOrStringArray").msgclass
  end
end
